services:
  # client:
  #   build:
  #     dockerfile: ./client/Dockerfile
  #   container_name: client
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=monke
  #     - RABBITMQ_DEFAULT_PASS=joaco1
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #       restart: true
  gateway :
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: gateway
    container_name: gateway
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  preprocessor:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: preprocessor
    container_name: preprocessor
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  production-filter:
    build:
      dockerfile: ./server/Dockerfile
      args:
          NODE: production-filter
    container_name: production-filter
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  year-filter:
    build:
      dockerfile: ./server/Dockerfile
      args:
          NODE: year-filter
    container_name: year-filter
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  joiner:
    build:
      dockerfile: ./server/Dockerfile
      args:
          NODE: joiner
    container_name: year-filter
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 2s
      timeout: 5s
      retries: 3

# volumes:
#   rabbitmq_data:  