name: tp-dist
services:

  gateway:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: gateway
    container_name: gateway
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 2s
      timeout: 5s
      retries: 3

  preprocessor-1:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: preprocessor
    container_name: preprocessor-1
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_SHARDS=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  preprocessor-2:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: preprocessor
    container_name: preprocessor-2
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_SHARDS=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  preprocessor-3:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: preprocessor
    container_name: preprocessor-3
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_SHARDS=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  production-filter-1:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: production-filter
    container_name: production-filter-1
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_SHARDS=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  production-filter-2:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: production-filter
    container_name: production-filter-2
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_SHARDS=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  year-filter-1:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: year-filter
    container_name: year-filter-1
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  year-filter-2:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: year-filter
    container_name: year-filter-2
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  sentiment-analyzer-1:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: sentiment-analyzer
    container_name: sentiment-analyzer-1
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  sentiment-analyzer-2:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: sentiment-analyzer
    container_name: sentiment-analyzer-2
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  reducer-1:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: reducer
    container_name: reducer-1
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  reducer-2:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: reducer
    container_name: reducer-2
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  reducer-3:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: reducer
    container_name: reducer-3
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  reducer-4:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: reducer
    container_name: reducer-4
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  final-reducer-q2:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: final-reducer
    container_name: final-reducer-q2
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - QUERY_NUM=2
      - JOINER_SHARDS=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  final-reducer-q3:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: final-reducer
    container_name: final-reducer-q3
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - QUERY_NUM=3
      - JOINER_SHARDS=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  final-reducer-q4:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: final-reducer
    container_name: final-reducer-q4
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - QUERY_NUM=4
      - JOINER_SHARDS=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  final-reducer-q5:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: final-reducer
    container_name: final-reducer-q5
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - QUERY_NUM=5
      - JOINER_SHARDS=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  joiner-1:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: joiner
    container_name: joiner-1
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_ID=1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  joiner-2:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: joiner
    container_name: joiner-2
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_ID=2
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  joiner-3:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: joiner
    container_name: joiner-3
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_ID=3
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  joiner-4:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: joiner
    container_name: joiner-4
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_ID=4
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  joiner-5:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: joiner
    container_name: joiner-5
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - JOINER_ID=5
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  client1:
    container_name: client1
    build:
      dockerfile: ./client/Dockerfile
    environment:
      - CLI_ID=1
    depends_on:
      - gateway
    volumes:
      - ./archive/:/home/app/archive/
      - ./client-results/:/home/app/results/

  client2:
    container_name: client2
    build:
      dockerfile: ./client/Dockerfile
    environment:
      - CLI_ID=2
    depends_on:
      - gateway
    volumes:
      - ./archive/:/home/app/archive/
      - ./client-results/:/home/app/results/
