name: tp-dist
services:
  healer-1:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: healer
    container_name: healer-1
    environment:
      - HEALER_ID=1
      - HEALERS_AMOUNT=4
      - DELAY=3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yaml:/docker-compose.yaml
  healer-2:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: healer
    container_name: healer-2
    environment:
      - HEALER_ID=2
      - HEALERS_AMOUNT=4
      - DELAY=3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yaml:/docker-compose.yaml
  healer-3:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: healer
    container_name: healer-3
    environment:
      - HEALER_ID=3
      - HEALERS_AMOUNT=4
      - DELAY=3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yaml:/docker-compose.yaml

  healer-4:
    build:
      dockerfile: ./server/Dockerfile
      args:
        NODE: healer
    container_name: healer-4
    environment:
      - HEALER_ID=4
      - HEALERS_AMOUNT=4
      - DELAY=3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yaml:/docker-compose.yaml

