name: tp-dist
services:
  client:
    build:
      dockerfile: ./client/Dockerfile
    container_name: client
    depends_on:
      - gateway
    volumes:
        - ./archive/:/home/app/archive/

  gateway:
     build:
       dockerfile: ./server/Dockerfile
       args:
         NODE: gateway
     container_name: gateway
     environment:
       - RABBITMQ_DEFAULT_USER=monke
       - RABBITMQ_DEFAULT_PASS=joaco1
     depends_on:
       rabbitmq:
         condition: service_healthy
         restart: true
  preprocessor:
     build:
       dockerfile: ./server/Dockerfile
       args:
         NODE: preprocessor
     container_name: preprocessor
     environment:
       - RABBITMQ_DEFAULT_USER=monke
       - RABBITMQ_DEFAULT_PASS=joaco1
     depends_on:
       rabbitmq:
         condition: service_healthy
         restart: true
  production-filter:
     build:
       dockerfile: ./server/Dockerfile
       args:
           NODE: production-filter
     container_name: production-filter
     environment:
       - RABBITMQ_DEFAULT_USER=monke
       - RABBITMQ_DEFAULT_PASS=joaco1
     depends_on:
       rabbitmq:
         condition: service_healthy
         restart: true
  year-filter:
    build:
      dockerfile: ./server/Dockerfile
      args:
          NODE: year-filter
    container_name: year-filter
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  joiner:
    build:
      dockerfile: ./server/Dockerfile
      args:
          NODE: joiner
    container_name: joiner
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  reducer:
    build:
      dockerfile: ./server/Dockerfile
      args:
          NODE: reducer
    container_name: reducer
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  final-reducer-q2:
    build:
      dockerfile: ./server/Dockerfile
      args:
          NODE: final-reducer
    container_name: final-reducer-q2
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - QUERY_NUM=2
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  final-reducer-q3:
    build:
      dockerfile: ./server/Dockerfile
      args:
          NODE: final-reducer
    container_name: final-reducer-q3
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
      - QUERY_NUM=3
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=monke
      - RABBITMQ_DEFAULT_PASS=joaco1
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 2s
      timeout: 5s
      retries: 3
